version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file:
      - db.env
  web:
    build: .
    image: ctd-itmo/coffee:2021.1
    restart: always
    volumes:
      - ./coffee:/app/coffee
      - ./config:/app/config
    ports:
      - 127.0.0.1:13338:80
